name: the_cook
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.0
  csv: ^6.0.0
  get: ^4.7.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/card_data.csv
    - assets/cards/Don/
    - assets/cards/EB01/
    - assets/cards/EB02/
    - assets/cards/OP01/
    - assets/cards/OP02/
    - assets/cards/OP03/
    - assets/cards/OP04/
    - assets/cards/OP05/
    - assets/cards/OP06/
    - assets/cards/OP07/
    - assets/cards/OP08/
    - assets/cards/OP09/
    - assets/cards/OP10/
    - assets/cards/OP11/
    - assets/cards/OP12/
    - assets/cards/OP13/
    - assets/cards/P/
    - assets/cards/PRB01/
    - assets/cards/PRB02/
    - assets/cards/ST01/
    - assets/cards/ST02/
    - assets/cards/ST03/
    - assets/cards/ST04/
    - assets/cards/ST05/
    - assets/cards/ST06/
    - assets/cards/ST07/
    - assets/cards/ST08/
    - assets/cards/ST09/
    - assets/cards/ST10/
    - assets/cards/ST11/
    - assets/cards/ST12/
    - assets/cards/ST13/
    - assets/cards/ST14/
    - assets/cards/ST15/
    - assets/cards/ST16/
    - assets/cards/ST17/
    - assets/cards/ST18/
    - assets/cards/ST19/
    - assets/cards/ST20/
    - assets/cards/ST21/
    - assets/cards/ST22/
    - assets/cards/ST23/
    - assets/cards/ST24/
    - assets/cards/ST25/
    - assets/cards/ST26/
    - assets/cards/ST27/
    - assets/cards/ST28/
